// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuniClear.Data;

#nullable disable

namespace MuniClear.Data.Migrations
{
    [DbContext(typeof(MuniClearContext))]
    [Migration("20260510005335_RenameCurrentBalanceToOutstandingBalance")]
    partial class RenameCurrentBalanceToOutstandingBalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("MuniClear.Data.Models.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ArrearsBalance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OutstandingBalance")
                        .HasColumnType("REAL");

                    b.Property<int>("PropertyID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountID");

                    b.HasIndex("PropertyID")
                        .IsUnique();

                    b.HasIndex("ResidentID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MuniClear.Data.Models.AdminUser", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdminID");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Bills", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingMonth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ElectricityCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("RefuseCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("SewerCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("WaterCharge")
                        .HasColumnType("REAL");

                    b.HasKey("BillID");

                    b.HasIndex("AccountID");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("MuniClear.Data.Models.ElectricityPurchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseID");

                    b.HasIndex("AccountID");

                    b.ToTable("ElectricityPurchases");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Fault", b =>
                {
                    b.Property<int>("FaultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FaultID");

                    b.HasIndex("AccountID");

                    b.ToTable("Faults");
                });

            modelBuilder.Entity("MuniClear.Data.Models.MobilePurchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseID");

                    b.HasIndex("AccountID");

                    b.ToTable("MobilePurchases");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationID");

                    b.HasIndex("AccountID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MuniClear.Data.Models.PasskeyCredential", b =>
                {
                    b.Property<int>("CredentialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialIdB64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeyB64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SignCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("CredentialID");

                    b.HasIndex("ResidentID");

                    b.ToTable("PasskeyCredentials");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentID");

                    b.HasIndex("AccountID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MuniClear.Data.Models.PaymentPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InterestRate")
                        .HasColumnType("REAL");

                    b.Property<double>("MonthlyInstalment")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("NextPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("PaidToDate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TermMonths")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalArrears")
                        .HasColumnType("REAL");

                    b.HasKey("PlanID");

                    b.HasIndex("AccountID");

                    b.ToTable("PaymentPlans");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PropertyID");

                    b.HasIndex("ResidentID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Resident", b =>
                {
                    b.Property<int>("ResidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("SA_IDNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("ResidentID");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Transaction", b =>
                {
                    b.Property<int>("TxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TxID");

                    b.HasIndex("AccountID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MuniClear.Data.Models.UnblockRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("POP_Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequestID");

                    b.HasIndex("AccountID");

                    b.ToTable("UnblockRequests");
                });

            modelBuilder.Entity("MuniClear.Data.Models.WaterReading", b =>
                {
                    b.Property<int>("ReadingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LeakAlert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Reading")
                        .HasColumnType("REAL");

                    b.Property<double>("Usage")
                        .HasColumnType("REAL");

                    b.HasKey("ReadingID");

                    b.HasIndex("AccountID");

                    b.ToTable("WaterReadings");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Account", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Property", "Property")
                        .WithOne("Account")
                        .HasForeignKey("MuniClear.Data.Models.Account", "PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuniClear.Data.Models.Resident", "Resident")
                        .WithMany("Accounts")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Bills", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany("Bills")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.ElectricityPurchase", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Fault", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.MobilePurchase", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Notification", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.PasskeyCredential", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Payment", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany("Payment")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.PaymentPlan", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Property", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Resident", "Resident")
                        .WithMany("Properties")
                        .HasForeignKey("ResidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Transaction", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.UnblockRequest", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.WaterReading", b =>
                {
                    b.HasOne("MuniClear.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Account", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Payment");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Property", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("MuniClear.Data.Models.Resident", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
